core/urls.py
from django.urls import path
from core import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("",views.index,name="index"),
    #product
    path("products/",views.product_list_view, name="products"),
    path("products/category/<cid>",views.category_product_list_view, name="category-list"),
    path("products/<pid>",views.product_detail_view, name="product-detail"),
    path("filter-product/",views.filter_product,name="filter-product"),
    path("add-to-cart/", views.add_to_cart, name="add-to-cart"),
    
    #vendors
    path("vendors/",views.vendor_list_view, name = "vendor-list"),
    path("vendors/<vid>",views.vendor_detail_view, name = "vendor-detail"),
    
    
    # tags
    
    path("prodcuts/tag/<slug:tag_slug>",views.tag_list, name="tags"),
    path("search/",views.serch_veiw,name="search"),
    
    
]

if settings.DEBUG:
    
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecomprjt/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('user/',include('userauths.urls')),
    path('ckeditor/',include('ckeditor_uploader.urls')),
]

userauths/urls.py
from django.urls import path
from userauths import views

app_name = "userauths"

urlpatterns = [
    
    path("sign-up/",views.register_view, name="sign-up"),
    path("sign-in/",views.login_view, name="sign-in"),
    path("sign-out/",views.logout_view, name="sign-out"),
]

templates/partials/category.html
{% load static %}
<div class="departments__body">
    <div class="departments__links-wrapper">
        <ul class="departments__links">  
            {% for c in categories %} 
            <li class="departments__item"><a href="{% url "category-list" c.cid %}">{{ c.title }}</a></li>
            {% endfor %}
            <li class="departments__item"><a href="{% url "products"  %}">All</a></li>
        </ul>
    </div>
</div><button class="departments__button" id="departments__button"><svg class="departments__button-icon"
        width="18px" height="14px">
        <use xlink:href="images/sprite.svg#menu-18x14"></use>
    </svg> Shop By Category <svg class="departments__button-arrow" width="9px"
        height="6px">
        <use xlink:href="images/sprite.svg# arrow-rounded-down-9x6"></use>
    </svg></button>

templates/partials/middleheader.html
{% load static %}
<div class="site-header__middle container">
    <div class="site-header__logo"><a href="{% url "index" %}"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 196 26" width="196" height="26">
        <!-- Your path element here -->
            
        <!-- Add your site name text -->
        <text x="10" y="20"   font-family="Arial, sans-serif" font-size="24" font-weight="bold" fill="#000" >E-com</text>
    </svg>
    </a></div>
    <div class="site-header__search">
        <div class="search">
            <form class="search__form" action="{% url "search" %}" method="GET"><input class="search__input" name="q"
                    placeholder="Search over 10,000 products" aria-label="Site search" type="text"
                    autocomplete="off"> 
                    <button class="fas fa-search" style="background: inherit;
                    color: green;
                    border: none;" type="submit"></button>
                <div class="search__border"></div>
            </form>
        </div>
    </div>
    <div class="site-header__phone">
        <div class="site-header__phone-title">Customer Service</div>
        <div class="site-header__phone-number">(800) 060-0730</div>
    </div>
</div>

templates/partials/topbar.html
{% load static %}
<div class="site-header__topbar topbar">
    <div class="topbar__container container">
        <div class="topbar__row">
            <div class="topbar__item topbar__item--link"><a class="topbar-link"
                    href="about-us.html">About Us</a></div>
            <div class="topbar__item topbar__item--link"><a class="topbar-link"
                    href="contact-us.html">Contacts</a></div>
            <div class="topbar__item topbar__item--link"><a class="topbar-link" href="#">Store
                    Location</a></div>
            <div class="topbar__item topbar__item--link"><a class="topbar-link"
                    href="track-order.html">Track Order</a></div>
            <div class="topbar__item topbar__item--link"><a class="topbar-link"
                    href="blog-classic.html">Blog</a></div>
            <div class="topbar__spring"></div>
            <div class="topbar__item">
                <div class="topbar-dropdown"><button class="topbar-dropdown__btn" type="button">My
                        Account <svg width="7px" height="5px">
                            <use xlink:href="{% static 'images/sprite.svg #arrow-rounded-down-7x5' %}"></use>
                        </svg>
                        </button>
                    <div class="topbar-dropdown__body"><!-- .menu -->
                        <ul class="menu menu--layout--topbar">
                            {% if user.is_authenticated %}
                            <li><a href="{% url "userauths:sign-up" %}">Register</a></li>
                            <li><a href="{% url "userauths:sign-out" %}">logout</a></li>
                            {% else %}
                            <li><a href="{% url "userauths:sign-in" %}">login</a></li>     
                            <li><a href="{% url "userauths:sign-up" %}">Register</a></li>
                            {% endif %}

                            <li><a href="#">Orders</a></li>
                            <li><a href="#">Addresses</a></li>
                        </ul><!-- .menu / end -->
                    </div>
                </div>
            </div>
            <div class="topbar__item">
                <div class="topbar-dropdown"><button class="topbar-dropdown__btn"
                        type="button">Currency: <span class="topbar__item-value">USD</span> <svg width="7px" height="5px">
                            <use xlink:href="{% static 'images/sprite.svg #arrow-rounded-down-7x5' %}"></use>
                        </svg>
                        </button>
                    <div class="topbar-dropdown__body"><!-- .menu -->
                        <ul class="menu menu--layout--topbar">
                            <li><a href="#">€ Euro</a></li>
                            <li><a href="#">£ Pound Sterling</a></li>
                            <li><a href="#">$ US Dollar</a></li>
                            <li><a href="#">₽ Russian Ruble</a></li>
                        </ul><!-- .menu / end -->
                    </div>
                </div>
            </div>
            <div class="topbar__item">
                <div class="topbar-dropdown"><button class="topbar-dropdown__btn"
                        type="button">Language: <span class="topbar__item-value">EN</span></button>
                        <div class="topbar-dropdown__body"><!-- .menu -->
                            <ul class="menu menu--layout--topbar menu--with-icons">
                                <li><a href="#">
                                    <div class="menu__icon"><img
                                        srcset="{% static 'images/languages/language-1.png' %}, {% static 'images/languages/language-1@2x.png' %} 2x"
                                        src="{% static 'images/languages/language-1.png' %}" alt=""></div>English
                                    </a></li>
                                <li><a href="#">
                                    <div class="menu__icon"><img
                                        srcset="{% static 'images/languages/language-2.png' %}, {% static 'images/languages/language-2@2x.png' %} 2x"
                                        src="{% static 'images/languages/language-2.png' %}" alt=""></div>French
                                    </a></li>
                                <li><a href="#">
                                    <div class="menu__icon"><img
                                        srcset="{% static 'images/languages/language-3.png' %}, {% static 'images/languages/language-3@2x.png' %} 2x"
                                        src="{% static 'images/languages/language-3.png' %}" alt=""></div>German
                                    </a></li>
                                <li><a href="#">
                                    <div class="menu__icon"><img
                                        srcset="{% static 'images/languages/language-4.png' %}, {% static 'images/languages/language-4@2x.png' %} 2x"
                                        src="{% static 'images/languages/language-4.png' %}" alt=""></div>Russian
                                    </a></li>
                                <li><a href="#">
                                    <div class="menu__icon"><img
                                        srcset="{% static 'images/languages/language-5.png' %}, {% static 'images/languages/language-5@2x.png' %} 2x"
                                        src="{% static 'images/languages/language-5.png' %}" alt=""></div>Italian
                                    </a></li>
                            </ul><!-- .menu / end -->
                        </div>                        
                </div>
            </div>
        </div>
    </div>
</div>